-- 초기 스키마(설계서 6장 "데이터 모델").
-- 원칙: OCR 원문(ocr_result)과 검수본(problem)을 분리하고 원문은 고치지 않는다.
--       문제지 문항(worksheet_item)은 문제 내용의 스냅샷을 가져 문제은행이 바뀌어도 그대로 재현된다.
--       이미지·형식 파일은 디스크에 두고 DB에는 저장소 기준 상대 경로만 둔다.

-- ---------- 사진 → OCR ----------

CREATE TABLE upload_batch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    textbook    VARCHAR(200) NOT NULL,
    grade       VARCHAR(10)  NOT NULL,
    folder_name VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE source_image (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_batch_id BIGINT       NOT NULL REFERENCES upload_batch (id),
    file_path       VARCHAR(500) NOT NULL,
    -- 같은 사진을 다시 OCR하지 않기 위한 중복 검사(설계서 5장 1단계)
    sha256          CHAR(64)     NOT NULL UNIQUE,
    downscaled      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP    NOT NULL
);

CREATE TABLE ocr_job (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_image_id BIGINT        NOT NULL REFERENCES source_image (id),
    status          VARCHAR(20)   NOT NULL,
    attempts        INT           NOT NULL DEFAULT 0,
    error_message   VARCHAR(2000),
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL
);
CREATE INDEX idx_ocr_job_status ON ocr_job (status);

-- 읽기 전용 원문. 수정하는 코드를 두지 않는다(CLAUDE.md 절대 원칙 1)
CREATE TABLE ocr_result (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_image_id BIGINT      NOT NULL REFERENCES source_image (id),
    engine          VARCHAR(30) NOT NULL,
    raw_json        CLOB        NOT NULL,
    text            CLOB,
    line_data       CLOB,
    created_at      TIMESTAMP   NOT NULL
);

-- ---------- 문제은행 ----------

CREATE TABLE problem_group (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stem_markdown CLOB      NOT NULL,
    version       BIGINT    NOT NULL DEFAULT 0,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL
);

CREATE TABLE problem (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id          BIGINT REFERENCES problem_group (id),
    -- 묶음 안 순서(설계서에 없던 칸: 원고 조립에 필요)
    group_order       INT,
    -- "복제해서 변형"한 문제의 원본
    origin_problem_id BIGINT REFERENCES problem (id),
    textbook          VARCHAR(200),
    grade             VARCHAR(10),
    page              INT,
    original_number   VARCHAR(20),
    type              VARCHAR(10)   NOT NULL,
    answer            VARCHAR(1000),
    answer_status     VARCHAR(10)   NOT NULL,
    -- 검수본 발문(보기 ①~⑤ 제외). <보기> 상자는 본문 안의 ::: bogi 구역
    body_markdown     CLOB          NOT NULL,
    -- LaTeX 명령어를 걷어낸 검색용 텍스트(설계서 4장 "본문 검색은 LIKE")
    search_text       CLOB          NOT NULL,
    review_status     VARCHAR(20)   NOT NULL,
    hold_memo         VARCHAR(1000),
    version           BIGINT        NOT NULL DEFAULT 0,
    deleted_at        TIMESTAMP,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL,
    CONSTRAINT ck_problem_type CHECK (type IN ('CHOICE', 'SHORT', 'ESSAY')),
    CONSTRAINT ck_problem_answer_status CHECK (answer_status IN ('ENTERED', 'LATER')),
    CONSTRAINT ck_problem_review_status CHECK (review_status IN ('SPLIT_PENDING', 'REVIEW_PENDING', 'ON_HOLD', 'CONVERT_ERROR', 'DONE'))
);
CREATE INDEX idx_problem_bank ON problem (review_status, deleted_at, created_at);
CREATE INDEX idx_problem_textbook ON problem (textbook, grade);
CREATE INDEX idx_problem_group ON problem (group_id, group_order);

-- 문제가 차지하는 사진 영역. 두 장에 걸치면 2개
CREATE TABLE problem_region (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id      BIGINT NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    source_image_id BIGINT NOT NULL REFERENCES source_image (id),
    x               INT    NOT NULL,
    y               INT    NOT NULL,
    width           INT    NOT NULL,
    height          INT    NOT NULL,
    sort_order      INT    NOT NULL
);

CREATE TABLE choice (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id       BIGINT  NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    number           INT     NOT NULL,
    content_markdown CLOB    NOT NULL,
    image_type       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_choice_number UNIQUE (problem_id, number),
    CONSTRAINT ck_choice_number CHECK (number BETWEEN 1 AND 5)
);

CREATE TABLE figure (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id    BIGINT REFERENCES problem (id) ON DELETE CASCADE,
    group_id      BIGINT REFERENCES problem_group (id) ON DELETE CASCADE,
    -- 본문의 [그림:p0123_1] 표시 이름(설계서에 없던 칸: 표시와 파일을 잇는다)
    marker        VARCHAR(50)  NOT NULL UNIQUE,
    file_path     VARCHAR(500) NOT NULL,
    sort_order    INT          NOT NULL,
    -- 단 너비 대비 %(30/50/80/100)
    display_width INT          NOT NULL DEFAULT 50,
    CONSTRAINT ck_figure_owner CHECK ((problem_id IS NULL) <> (group_id IS NULL)),
    CONSTRAINT ck_figure_width CHECK (display_width IN (30, 50, 80, 100))
);

CREATE TABLE tag (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE problem_tag (
    problem_id BIGINT NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES tag (id),
    PRIMARY KEY (problem_id, tag_id)
);

-- ---------- 문제지 ----------

CREATE TABLE template (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100)  NOT NULL UNIQUE,
    file_path      VARCHAR(500)  NOT NULL,
    column_count   INT           NOT NULL,
    -- 보기 배치 기준 칸 수(설계서 13장 10-06 결정: 형식별 설정)
    choices5_max   INT           NOT NULL,
    choices3_max   INT           NOT NULL,
    space_choice   DECIMAL(4, 1) NOT NULL,
    space_short    DECIMAL(4, 1) NOT NULL,
    space_essay    DECIMAL(4, 1) NOT NULL,
    -- 단 너비(cm). 그림 크기(%)를 cm로 바꿀 때 쓴다(설계서 9장)
    column_width   DECIMAL(4, 1) NOT NULL,
    built_in       BOOLEAN       NOT NULL,
    created_at     TIMESTAMP     NOT NULL
);

-- 문제지 번호 WS-0001 …
CREATE SEQUENCE worksheet_number_seq START WITH 1;

CREATE TABLE worksheet (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number             VARCHAR(20)  NOT NULL UNIQUE,
    title              VARCHAR(200) NOT NULL,
    worksheet_date     DATE         NOT NULL,
    template_id        BIGINT       NOT NULL REFERENCES template (id),
    duplicated_from_id BIGINT REFERENCES worksheet (id),
    version            BIGINT       NOT NULL DEFAULT 0,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL
);

CREATE TABLE worksheet_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_id     BIGINT      NOT NULL REFERENCES worksheet (id) ON DELETE CASCADE,
    -- 휴지통에서 30일 뒤 실제로 지워지면 NULL. 스냅샷이 있어 문제지는 그대로 재현된다
    problem_id       BIGINT REFERENCES problem (id) ON DELETE SET NULL,
    sort_order       INT         NOT NULL,
    space_size       VARCHAR(10) NOT NULL,
    snapshot         CLOB        NOT NULL,
    snapshot_version BIGINT      NOT NULL,
    CONSTRAINT ck_item_space CHECK (space_size IN ('SMALL', 'NORMAL', 'LARGE'))
);
CREATE INDEX idx_worksheet_item ON worksheet_item (worksheet_id, sort_order);

-- ---------- 운영 ----------

CREATE TABLE api_usage (
    year_month    CHAR(7) PRIMARY KEY,
    call_count    INT NOT NULL DEFAULT 0,
    page_estimate INT NOT NULL DEFAULT 0
);
